{% set version = "0.1.0" %}

package:
  name: xeus-eta
  version: {{ version }}

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.28
    - ninja
  host:
    - xeus >=5,<6
    - xeus-zmq >=3,<4
    - libtorch
    - nng
    - eigen
    - nlohmann_json
  run:
    - xeus >=5,<6
    - xeus-zmq >=3,<4
    - libtorch

test:
  commands:
    - eta_jupyter --version
    - eta_jupyter --install --prefix=%PREFIX%

about:
  home: https://github.com/eta-lang/eta
  summary: "Eta Jupyter kernel powered by xeus"
  license: MIT
